name: Node.js 24/7 Bot with Failover

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */7 * * *'  # Restart every 7 hours
  workflow_dispatch:        # Manual start if needed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start bot with auto-restart (7h max)
      run: |
        echo "🚀 Starting bot with failover (7h max)..."
        end=$((SECONDS+25200))   # 25200s = 7h
        while [ $SECONDS -lt $end ]; do
          echo "▶️ Launching bot..."
          npm start || echo "⚠️ Bot crashed, restarting..."
          sleep 5
        done
        echo "⏹ Bot reached 7h limit, waiting for next cron restart."
